# Generated by Django 5.2.7 on 2025-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
