# Generated by Django 5.2.7 on 2025-10-16 06:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_additional_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{7,15}$')])),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='quotation.quotation')),
            ],
        ),
    ]
