# Generated by Django 5.2.7 on 2025-10-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotationinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationinfo',
            old_name='quotation_title',
            new_name='quotation_to',
        ),
    ]
