# Generated by Django 5.2.7 on 2025-10-16 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_alter_quotationinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in one of these formats: '+9779814714838', '+977-9819191818', '+977 9819191818', '01-40000000', or '01xxxxxxx'.", regex='^(\\+977[- ]?\\d{7,10}|0\\d{1,2}[- ]?\\d{6,8})$')]),
        ),
    ]
