# Generated by Django 5.2.7 on 2025-10-17 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_alter_quotationinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='version',
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='custom_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Piece'), ('m', 'Meter')], max_length=50),
        ),
    ]
