# Generated by Django 5.2.7 on 2025-10-17 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_remove_quotationitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
