# Generated by Django 5.2.7 on 2025-10-30 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_alter_quotation_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='validation_date',
            field=models.DateField(blank=True, help_text='Optional date until which the quotation is valid.', null=True),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in one of these formats: '+9779814716361', '+977-9819191818', '+977 9819191818', '01-40000000', or '01xxxxxxx'.", regex='^\\+(0?[1-9][0-9]{0,2})[- ]?\\d{7,10}$')]),
        ),
    ]
