# Generated by Django 5.2.7 on 2025-10-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_quotation_validation_date_alter_quotationinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='validation_date',
            new_name='validity_date',
        ),
    ]
