# Generated by Django 5.2.7 on 2025-11-02 04:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_quotation_quotation_number_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotation_q_quotati_c14297_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['lead_id'], name='quotation_q_lead_id_861ae7_idx'),
        ),
    ]
