# Generated by Django 5.2.7 on 2025-11-02 05:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0016_alter_quotation_status_alter_quotation_validity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))]),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in one of these formats: '+9779814716361', '+977-9819191818', '+977 9819191818', '01-40000000', or '01xxxxxxx'.", regex='^\\+(0?[1-9][0-9]{0,2})[- ]?\\d{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name can only contain letters, numbers, spaces, hyphens, commas, periods, and parentheses.', regex='^[A-Za-z0-9\\s\\-,.()]+$')]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Piece'), ('m', 'Meter')], max_length=50),
        ),
    ]
