# Generated by Django 5.2.7 on 2025-11-02 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0017_alter_quotation_vat_alter_quotationinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid.', regex='^\\+(0?[1-9][0-9]{0,2})[- ]?\\d{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, hyphens, commas, periods, and parentheses.', regex='^[A-Za-z0-9\\s\\-,.()]+$')]),
        ),
    ]
