# Generated by Django 5.2.7 on 2025-11-02 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_alter_quotationinfo_phone_alter_quotationitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, hyphens, commas, periods, and parentheses.', regex="^[A-Za-z0-9\\s\\-\\.,'()]+$")]),
        ),
    ]
