# Generated by Django 5.2.7 on 2025-11-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_alter_quotationitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='custom_unit',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_data',
            field=models.JSONField(default=dict),
        ),
    ]
