# Generated by Django 5.2.7 on 2025-11-04 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0020_remove_quotationitem_custom_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid.', regex='^\\+(0?[1-9][0-9]{0,2})[- ]?\\d{7,10}$')]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='QuotationInfo',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
